name: Publish Library

# When a release is published
on:
  release:
    types: [published]
jobs:
  build:
    # 2019, has our .NET needs, latest does not
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    # While this package targets .Net Framework 4.6.2, the dotnet 7 stuff will work.
    - name: Get version
      run: |
        VERSION=${{ github.event.release.tag_name }}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
    - name: Read version
      run: |
        echo Version now: ${VERSION}
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${VERSION}
    - name: cd into Library
      run: cd Elements.Quantity
    - name: Pack
      run: dotnet pack --output nupkgs --configuration Release /p:Version=${VERSION} /p:PackageVersion=${VERSION}
    - name: Nuget Publish
      run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json