name: Whatever

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Get version
      run: echo "VERSION=7" >> "$GITHUB_ENV"
    - name: Read version
      run: |
        echo Version now: ${VERSION}